version: '3.8'

services:
  video-processor:
    build: .
    container_name: video-processor
    volumes:
      - ./.env:/app/.env
      - ./logs:/app/logs
      - ./backup:/app/backup
      - ./processed:/app/processed
    restart: unless-stopped
